name: backend
description: A REST API backend for a flutter app that manages SWP groups during the 2024/2025 semester at the University of Bremen.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  corsac_jwt: ^1.0.0-nullsafety.1
  cryptography: ^2.7.0
  drift: ^2.18.0
  email_validator: ^3.0.0
  http: ^1.2.1
  logger: ^2.3.0
  mailer: ^6.1.0
  path: ^1.9.0
  #path_provider: ^2.1.3
  shelf: ^1.4.1 # Cannot use 1.4.2 as of now, because of collection 1.19.0 dep.
  shelf_open_api_generator: ^2.0.0
  shelf_router: ^1.1.4
  shelf_router_generator: ^1.1.0
  shelf_static: ^1.1.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  flutter_lints: ^3.0.2
  lints: ^3.0.0
  test: ^1.24.0
